### PR TITLE
Add files to run TulipaEnergyModel.jl cases

### PR DESCRIPTION
**Pull request by datejada**
@odow and @joaquimg I took the files from GenX and Sienna folders as a reference. I ran this case study for a simplified version of a European investment problem. I can add more, but I want to first check that everything works properly. For instance, I can run this code locally, but if I try to write the instance files, I get an error. I mean:

This code runs without error:
```cmd
julia --project=TulipaEnergyModel TulipaEnergyModel/main.jl --all --run
```

This code runs with errors:
```cmd
julia --project=TulipaEnergyModel TulipaEnergyModel/main.jl --all --run --write
```

```log
Error running C:\github-repos\open-energy-modeling-benchmarks\TulipaEnergyModel\cases\1_EU_investment_simple
e = Base.IOError("could not spawn `gzip 'C:\\github-repos\\open-energy-modeling-benchmarks\\instances\\tmp.mps'`: no such file or directory (ENOENT)", -4058)
```

Anyway, we can discuss in the next meeting more details

### CODE REVIEW

**Comment by datejada** [comment]
@odow and @joaquimg, sorry, one more thing: the case study "1_EU_investment_simple" can be solved with commercial solvers in my local machine, but it seems like HiGHS "freezes" after a couple of iterations in the B&B. I couldn't double-check it because I stopped the run after 10 minutes without any signal. So, if the same happens to you, then we have another interesting .mps file to improve HiGHS; if not, I might need a better PC 😝 

Thanks!

**Comment by odow** [comment]
Thanks! I'll take a look

**Comment by odow** [comment]
I can reproduce the stall (but not the write issue)
```
(base) oscar@Oscars-MBP open-energy-modeling-benchmarks % julia --project=TulipaEnergyModel TulipaEnergyModel/main.jl --all --run --write 
The latest version of Julia in the `1.10` channel is 1.10.6+0.x64.apple.darwin14. You currently have `1.10.5+0.x64.apple.darwin14` installed. Run:

  juliaup update

in your terminal shell to install Julia 1.10.6+0.x64.apple.darwin14 and update the `1.10` channel to that version.
[ Info: Running /Users/oscar/.julia/dev/open-energy-modeling-benchmarks/TulipaEnergyModel/cases/1_EU_investment_simple
Running HiGHS 1.8.0 (git hash: fcfb53414): Copyright (c) 2024 HiGHS under MIT licence terms
Writing the model to /Users/oscar/.julia/dev/open-energy-modeling-benchmarks/instances/tmp.mps
WARNING: There are empty or excessively-long column names: using constructed names with prefix "c"
WARNING: There are empty or excessively-long row names: using constructed names with prefix "r"
Coefficient ranges:
  Matrix [3e-07, 4e+04]
  Cost   [2e+00, 4e+06]
  Bound  [1e+00, 4e+07]
  RHS    [3e-07, 9e+07]
Presolving model
850993 rows, 1465904 cols, 3875096 nonzeros  2s
765359 rows, 1384318 cols, 3569839 nonzeros  9s

Solving MIP model with:
   765359 rows
   1384318 cols (8 binary, 239 integer, 0 implied int., 1384071 continuous)
   3569839 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   -inf            inf                  inf        0      0      0         0    13.5s
 S       0       0         0   0.00%   -inf            10114494154.6      Large        0      0      0         0   197.8s
^C
[73332] signal (2): Interrupt: 2
in expression starting at /Users/oscar/.julia/dev/open-energy-modeling-benchmarks/TulipaEnergyModel/main.jl:125
_ZN7HFactor11buildFinishEv at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN7HFactor5buildEP15HighsTimerClock at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN11HSimplexNla6invertEv at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN4HEkk13computeFactorEv at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN4HEkk21getNonsingularInverseEi at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN8HEkkDual7rebuildEv at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN8HEkkDual11solvePhase2Ev at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN8HEkkDual5solveEb at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN4HEkk5solveEb at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_Z14solveLpSimplexR19HighsLpSolverObject at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_Z7solveLpR19HighsLpSolverObjectNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN5Highs11callSolveLpER7HighsLpNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZZN5Highs3runEvENK3$_0clER7HighsLpRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEERd at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
_ZN5Highs3runEv at /Users/oscar/.julia/artifacts/6c052094bcce703903faeccc27a66f3453fd061e/lib/libhighs.1.8.dylib (unknown line)
```

**Comment by odow** [comment]
Can you `CTRL+C` to get a stack trace?

Edit: I ran a few times and it hit different places, so I think we're just iterating slowly.

**Comment by odow** [comment]
Can we make the problem smaller?

**Comment by odow** [comment]
Let's discuss in #25

**Pull request merged**
